uuid="replaced at run time"
destination="s3.us-west.cloud-object-storage.test.appdomain.cloud"
group=1
ordinal=6
instance_count=1
instance_name="acadia-perf-customize"
sku="cx2-2x4"
service="cpu"
test_provision="control-provision-customize"
test_terminate="control-terminate-customize"
test_data="acadia-perf-customize"
name_prefix="acadia-perf-customize"
volume_name="acadia-perf-vol-customize"
