FROM hashicorp/terraform:latest

ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools
RUN pip3 install python-dateutil

COPY . .

ENTRYPOINT ["sh", "/terraform.sh"]
CMD [ "dal", "", ""]
